name: Deploy application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up flutter-action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Detect formatting errors
        run: dart format --line-length 100 --set-exit-if-changed --output none .
      - name: Detect syntax errors
        run: flutter analyze --no-pub .
      - name: Build app
        run: flutter build web
      - name: move build directory into root folder
        run: mv -n ./build/web ./build/web2 && mv -n ./build/web2 ./
      - name: Remove folders
        run: rm -r .github assets lib web build
      - name: remove files 
        run: rm .gitignore .metadata analysis_options.yaml pre-commit pubspec.lock pubspec.yaml README.md
      - name: move build files into root folder
        run: mv -n ./web2/* ./ && rm -r web2
      - name: ls
        run: ls
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
          git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
          NO_PAGER=1 git --no-pager diff HEAD^